# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7eeaaac9efb421552d00a1fb2920afd2889f997f672d3a59ac702719b6f55beb0c58b7640d3eef173eed7ee8307e3060f13f47b43b3b7048d6da57573b50e01

test:
  secret_key_base: 8c45a09417db9d6ef0da73727269ae9817ddc98f1d133ff65c3dadde21aa29a5b2b5418d819c01997aaab220afab614962a6491bf19bb4389d8ac217a149a793

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
